apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service
  namespace: klinik-antrian
  labels:
    app: queue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-service
  template:
    metadata:
      labels:
        app: queue-service
    spec:
      containers:
        - name: queue-service
          image: klinik/queue-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: klinik-config
                  key: JWT_SECRET
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: klinik-config
                  key: QUEUE_DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: klinik-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: klinik-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: klinik-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: klinik-secret
                  key: DB_PASS
          livenessProbe:
            httpGet:
              path: /
              port: 5004
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
