apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: klinik-antrian
  labels:
    app: doctor-service
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
  selector:
    app: doctor-service
