apiVersion: v1
kind: ConfigMap
metadata:
  name: klinik-config
  namespace: klinik-antrian
  labels:
    app: klinik-antrian
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  JWT_SECRET: "klinikrahasia"
  AUTH_DB_NAME: "auth_db"
  DOCTOR_DB_NAME: "doctor_db"
  PATIENT_DB_NAME: "patient_db"
  QUEUE_DB_NAME: "queue_db"